language: php

php:
  - 5.3
  - 5.4

before_install:
  - git submodule update --init --recursive

script: phpunit --configuration packages/phrame/core/tests/phpunit.xml

notifications:
  email:
    - phrame@itworks.in.ua