language: php

php:
  - 5.3
  - 5.4

before_install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit --configuration packages/phrame/core/tests/phpunit.xml

notifications:
  email:
    - phrame@itworks.in.ua